### ISSUE TITLE
High Priority: Home Map

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#103] opened 2020-11-12 06:55 UTC
Location: spicygreenbook.com (Home Page). Scroll down to the map. 

Problem: This map has multiple issues across multiple states. I will list what I have seen in my interacting with this map paired with screenshots. 

1. Clicking on a city/metro area in the pop up window of a state takes you to an error 

<img width="1440" alt="Screen Shot 2020-11-11 at 10 44 11 PM" src="https://user-images.githubusercontent.com/69876068/98905523-67b84a00-2470-11eb-851f-ef31cf4f690a.png">

2. Clicking on a city/metro area in the pop up window of a state brings up all the listings instead of the one or select few in that city. E.g. Clicking on Tampa, FL which has one listing will take you to all of them across the nation. 

<img width="1440" alt="Screen Shot 2020-11-11 at 10 44 26 PM" src="https://user-images.githubusercontent.com/69876068/98905651-a0582380-2470-11eb-83b8-c6acffec2431.png">

<img width="1440" alt="Screen Shot 2020-11-11 at 10 45 36 PM" src="https://user-images.githubusercontent.com/69876068/98905660-a51cd780-2470-11eb-921d-2e0db6198912.png">

3. Clicking on a city/metro area in the pop up window of a state does not have a consistent quantity. E.g. the map shows that Denver, CO has two listings meanwhile we actually have 4 listings in Colorado 

<img width="1440" alt="Screen Shot 2020-11-11 at 10 47 38 PM" src="https://user-images.githubusercontent.com/69876068/98905745-cda4d180-2470-11eb-919c-1e1b175cd621.png">

<img width="1440" alt="Screen Shot 2020-11-11 at 10 47 26 PM" src="https://user-images.githubusercontent.com/69876068/98905754-d1385880-2470-11eb-9779-3f48c965ea9b.png">

Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by danielpquinn** [comment] 2020-11-13 02:13
I'm picking up this task

**Comment by danielpquinn** [comment] 2020-11-14 14:31
@danilobatson Here's where I ended up with this issue. Long story short I will probably need to hand this off to @pleaseshutup:

1. Clicking on a city/metro area in the pop up window of a state takes you to an error
**I could not reproduce this, are you still seeing this issue?**

2. Clicking on a city/metro area in the pop up window of a state brings up all the listings instead of the one or select few in that city. E.g. Clicking on Tampa, FL which has one listing will take you to all of them across the nation.
**I can't reproduce this one either. I think this happens when the geocode API goes down intermittently, maybe because of the way DynamoDB caching is set up? I will need @pleaseshutup to help fix this one**

3. Clicking on a city/metro area in the pop up window of a state does not have a consistent quantity. E.g. the map shows that Denver, CO has two listings meanwhile we actually have 4 listings in Colorado
**This is happening because the geo coordinates for some listings don't match their address. I think the suggestion is to update the listing's address so it matches the coordinates. There's some discussion about this in the pull request that I opened related to this issue**

**Comment by pleaseshutup** [comment] 2020-11-15 17:08
I'm not entirely sure there is a solution here that can/will be done in the code itself. Seems like an issue of ensuring that all listings are consistent and accurate with their geocordinates and addresses. 

For example, The Cookie Monster Cookies has the address set but does not have geocoordinates set. That's why it shows up when you click on florida in the SGBMAP widget but not in the listings google map on the right side of the page.

I'm going to close this. If you still come across issues will you please list them 1 bug at a time so we can focus on the exact issue and close it out vs having a ticket open trying organize on which items are fixed and which are not.

**Closed by pleaseshutup** 2020-11-15 17:08 UTC
Labels: bug
