### ISSUE TITLE
"Hiccup" when searching for restaurants

### ISSUE THREAD

**Issue by jabramso01** [spicygreenbook/greenbook-app#408] opened 2021-06-17 13:33 UTC
**Describe the bug**
Searching for Washington DC and initial results are San Francisco, then it re-directs/updates to DC.

**To Reproduce**
1. Go to https://spicygreenbook.org/
2. Search for Washington DC
3. See the "Hiccup" before the results are shown for DC

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/71447998/122406346-c685fa80-cf4e-11eb-8e36-5a0f4ed43f4d.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome
 - Version: Version 91.0.4472.101 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by danilobatson** [comment] 2021-08-02 20:48
@jabramso01  I was unable to replicate this issue. Is this still occuring for you? If not we can close this issue.

**Comment by jabramso01** [comment] 2021-08-02 21:05
Yes it still occurs. I just checked again.

**Comment by FuqingWang** [comment] 2021-08-04 03:11
@jabramso01 I think the "Hiccup" is what we expected, and it is caused by the map reload every time we do a new search. If we search "Boston MA" on google map then switch to "Seattle WA", we can see a similar brief hiccup before the result shows up. How long is the "Hiccup" on your end? On my end, it disappears within a glimpse of an eye which I think is totally acceptable.

**Comment by jabramso01** [comment] 2021-08-04 11:20
The hiccup is brief just wanted to share my experience.

**Comment by FuqingWang** [comment] 2021-08-04 13:40
I suggest we close this issue since the "Hiccup" is expected behavior caused by map reload.

**Comment by jabramso01** [comment] 2021-08-04 13:41
ok

**Closed** 2021-08-11 16:47 UTC
Labels: Status: Available, Priority: Medium, Type: Bug
